### ISSUE TITLE
Stuck at boot animation 

### ISSUE THREAD

**Issue by walker425** [ChonDoit/treble_superior_patches#9]
I tried to flash Android 14 of superior os but it's stuck at boot animation. My device is medietake infinix note 11.

**Comment by gramozdilla** [comment]
The animation does not load further

**Comment by gramozdilla** [comment]
https://github.com/ChonDoit/treble_superior_patches/issues/9#issuecomment-1925696255

**Comment by gramozdilla** [comment]
https://github.com/ChonDoit/treble_superior_patches/issues/9#issue-2116382877

**Comment by PinkSerenity** [comment]
Same with ProjectElixir. All other images I've tested have worked so far.

**Comment by Osanosa** [comment]
MTK g96, stock A12, same issue, adb unauthorized, can't read logs

**Comment by gramozdilla** [comment]
v20240204
The animation does not load further

**Comment by ankan2008** [comment]
same issues in lenovo tab k10 mediatek

**Comment by gramozdilla** [comment]
v20240212 
It doesn't load again. Switched to alphadroid.

**Comment by PinkSerenity** [comment]
> It doesn't load again. Switched to alphadroid.

Why AlphaDroid? It's Android 13 and hasn't been updated since October.
